### ISSUE TITLE
嵌入文档中，markdown-embed-content的自定义样式无法正确导出

### ISSUE THREAD

**Issue by MilaMianner** [zhouhua/obsidian-export-image#107]
大佬好，我试图给嵌入文档添加emoji，于是我编写了如下的css，并且添加到了obsidian的外观中：

``` css
/* 路径包含「手帐」时隐藏标题 + 显示同行图标 */
.markdown-embed[src*="手帐"] .markdown-embed-title {
  display: none !important;
}

/* 关键改动：将图标插入到内容容器内（非绝对定位） */
.markdown-embed[src*="手帐"] .markdown-embed-content {
  padding-left: 2.0em; /* 为图标腾出空间 */
  padding-right: 3.0em;
  position: relative;
}

.markdown-embed[src*="手帐"] .markdown-embed-content::before {
  content: "📝";
  position: absolute;
  left: 0; /* 固定在内容左侧 */
  font-size: 1.0em;
}

/* 路径包含「地点」的规则 */
.markdown-embed[src*="地点"] .markdown-embed-title::before {
  content: "🏘️";
  margin-right: 0.2em;
}
```

在obsidian中，编辑模式和预览模式下，我都能看到我添加的emoji：

![编辑模式下的显示](https://github.com/user-attachments/assets/0c79a060-8f77-4546-94bb-d0f5e909d273)

![预览模式下的显示](https://github.com/user-attachments/assets/38c4e2e9-106e-43c0-b336-e0185e67d730)

但在我想要导出的时候，添加在markdown-embed-title中的伪元素能够被正确导出，而添加在markdown-embed-content的则被忽略：

![导出图片时，添加在markdown-embed-content的伪元素无法渲染](https://github.com/user-attachments/assets/467ae0c4-2228-4515-b017-9b5c9a72b2cf)

此外，我尝试了修改markdown-embed-content的padding，使它更大，但是在导出的时候，padding仍然是默认的。

![更大的padding，在obsidian试图中可用](https://github.com/user-attachments/assets/5bf6b13e-ac2b-4fbb-834e-ed87cf85b8e1)

我想知道为什么，我通过css对markdown-embed-content自定义的样式无法导出？这是不是一个Bug？

您的插件非常好用，我是它的重度使用者，但是这个问题困扰了我挺久的。如果您能帮我解决这个问题，我非常感谢您。
