### ISSUE TITLE
当metadata中存在缩进关系时导出预览面板出错

### ISSUE THREAD

**Issue by ProudBenzene** [zhouhua/obsidian-export-image#29]
作者大大，我发现如果metadata中存在缩进情况，例如：

```yaml
title: '1984'
author: '乔治·奥威尔, 孙仲旭(译)'
tags: null
aliases: null
kindle-sync:
  bookId: '19717'
  title: 1984 (反乌托邦三部曲)
  author: '乔治·奥威尔, 孙仲旭(译)'
  highlightsCount: 45
```

则会产生这种错误，点击导出为图片后弹出的面板显示不正常：

<img width="1306" alt="image" src="https://github.com/zhouhua/obsidian-export-image/assets/93238080/10f6d684-6f89-42a1-b4d7-aaac50349c73">

另外还有一个CSS小问题，我使用您上次交给我的`.export-image-preview-container`貌似对metadata无效：

```css
.book.is-live-preview .metadata-container,
.book.markdown-preview-view .metadata-container,
.book .export-image-preview-container.markdown-preview-view .metadata-container, {
    position: absolute;
    display: block;
    width: calc(80% - 330px);
    left: calc(10% + 330px);
    max-height: 500px;
    overflow-y: scroll;
}
```

当我对其中的变量做出修改时，原笔记中metadata的展示形状会发生变化，但是导出预览中不会🫠如果您方便的话可否请您帮我看一下如何修改CSS可以使其对导出的metadata生效😢
