### ISSUE TITLE
[FR] Configurable image margin

### ISSUE THREAD

**Issue by alanhe** [zhouhua/obsidian-export-image#32]
**需求**
导出的图片有 `32px` 的 Margin。在手机上看的时候，两边有大白边，感觉有点儿浪费屏幕空间。
希望可以在 Image Export Preview 对话框中自定义 Margin。

**变通法**
可以通过 CSS snippets (https://help.obsidian.md/Extending+Obsidian/CSS+snippets) 覆盖默认样式。
缺点是只能配置一个全局样式，没法为每个导出图片单独修改。

```css
body .export-image-preview-root .markdown-preview-view {
    padding: 4px !important;
}
```
