### ISSUE TITLE
[FR] 增加选项以支持渲染背景

### ISSUE THREAD

**Issue by Moyf** [zhouhua/obsidian-export-image#82]
## 需求说明
像是 CodeSnap （VSC 拓展）可以生成这样的图片：
![image](https://github.com/user-attachments/assets/7440004b-0584-4752-838f-512ef0734896)

在背后添加一个纯色渐变的背景，并且将图片用带阴影的圆角矩形放在上面，感觉很好看 : )
如果有兴趣的话，可以考虑添加类似的特性吗？

___

## 可能相关
[Recoded](https://github.com/siddharthroy12/recoded) 这个开源项目也支持类似的效果

从多种预置的背景色中选择并应用：
![image](https://github.com/user-attachments/assets/734db2ec-2276-4686-9c65-01f98d6b3903)

**Comment by Moyf** [comment]
似乎相关： #94 

不过这个 Issue 主要是针对 *纯色* 或者 *渐变颜色*，应该可以只通过 CSS 实现。

以及，如果更进一步的话，似乎可以同时支持设置“图片背景”和“正文背景”两套 Background 🤔

（不过那样工作量就更大了，haha）

**Comment by Moyf** [comment]
刚才突发奇想试了一下，发现用 CSS Snipeets 就可以（一定程度）实现类似的效果！

例如：
![Image](https://github.com/user-attachments/assets/efe6bd81-16b1-4f5b-8efc-493db3b1aa81)

对应的 CSS：
```css
/* ! Export Image */

/* 外层背景 */
.export-image-root.markdown-reading-view {
    /* 好看的渐变背景色 */
    /* background-color: var(--background-primary) !important; */

    background: linear-gradient(45deg, #ff4e50, #f9d423);
}

/* 把 inline title 显示出来 */
.export-image-root .inline-title:not([data-level]) {
    display: block !important;
}

.export-image-root.markdown-reading-view > div:first-child {
    background-color: var(--background-secondary) !important;

    border-radius: 6px;
    margin: 2em;

    box-shadow: 0 0 6px #00000055;
}

.export-image-root.markdown-reading-view > div.user-info-container {
    /* 透明背景 */
    background-color: transparent !important;
    border: none !important;

    border-radius: 6px;
    margin-top: 0;
    margin-bottom: 10px;

    /* box-shadow: 0 0 6px #00000055; */
}
```
